import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { afterAll, describe, expect, it } from "vitest";
import type { FinishResponse } from "@/lib/game/types";
import type { TypingEvent } from "@/lib/scoring/types";
import { emptyBoards } from "@/test/empty-boards";
import { typed } from "@/test/typing-events";
import { verifyEverywhere } from "@/test/verified";
import { createDb } from "../db/client";
import { bests, games, keystrokeLogs, users } from "../db/schema";
import { createRanking } from "../leaderboard/ranking";
import { createLeaderboardStore } from "../leaderboard/store";
import { createRedis } from "../redis";
import { createSaveVerificationGame } from "../verification/finish";
import { decodeKeystrokeLog } from "./keystroke-log";
import { createSaveGame } from "./persist";
import { createGameService } from "./service";
import { createGameStore } from "./store";
import { DEV_ANTICHEAT_CONFIG } from "../anticheat/config";

const db = createDb(process.env.DATABASE_URL!);
const redis = createRedis(process.env.UPSTASH_REDIS_REST_URL!, process.env.UPSTASH_REDIS_REST_TOKEN!);
const rankingPrefix = `${process.env.REDIS_KEY_PREFIX}service-${randomUUID().slice(0, 8)}:`;
const leaderboard = createLeaderboardStore(redis, rankingPrefix);
const ranking = createRanking({ db, store: leaderboard, onTopChanged: () => {} });

// Short times to run whole games in the test: no countdown, a 1.5 s game.
const service = createGameService({
  store: createGameStore(redis, process.env.REDIS_KEY_PREFIX!),
  saveGame: createSaveGame(db),
  saveVerificationGame: createSaveVerificationGame(db),
  loadWords: async () => ["hola"],
  random: Math.random,
  newId: randomUUID,
  times: { countdownMs: 0, durationMs: 1_500, graceMs: 500 },
  anticheat: DEV_ANTICHEAT_CONFIG,
  rankGame: ranking.rankGame,
});

const ENV = { coarse: false, touchPoints: 0 };
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

afterAll(async () => {
  const keys = await redis.keys(`${rankingPrefix}*`);
  if (keys.length > 0) await redis.del(...keys);
  await db.$client.end();
});

async function storedReason(gameId: string) {
  const [row] = await db.select({ reason: games.rejectReason }).from(games).where(eq(games.id, gameId));
  return row?.reason;
}

async function play(
  events: TypingEvent[],
  { waitBeforeSend = 400, waitBeforeFinish = 0, userId = null as string | null, language = "es" as "es" | "pt" } = {},
) {
  const owner = randomUUID();
  const { gameId, words } = await service.start({ owner, userId, language, env: ENV });
  await sleep(waitBeforeSend);
  expect(await service.appendKeys({ owner, gameId, seq: 1, events })).toBe("ok");
  await sleep(waitBeforeFinish);
  const outcome = await service.finish({ owner, gameId, lastSeq: 1, ipHash: null });
  return { owner, gameId, words, outcome };
}

describe("GameService (Redis + PostgreSQL)", () => {
  it("an honest game is valid, scored on the server and saved", async () => {
    const { gameId, words, outcome } = await play(typed("hola ", { every: 50, hold: 30 }));
    expect(words.every((word) => word === "hola")).toBe(true);
    if (outcome.kind !== "ok") throw new Error(outcome.kind);
    expect(outcome.response).toMatchObject({
      gameId,
      verdict: "valid",
      reason: null,
      inputType: "physical",
      correctChars: 5,
      ranking: { kind: "would_rank" },
    });

    const [row] = await db.select().from(games).where(eq(games.id, gameId));
    expect(row).toMatchObject({ verdict: "valid", wpm: outcome.response.wpm });
    const [log] = await db.select().from(keystrokeLogs).where(eq(keystrokeLogs.gameId, gameId));
    expect(decodeKeystrokeLog(log.events)?.words).toEqual(words);
  });

  it("repeating the finish returns the same result without saving it again", async () => {
    const { owner, gameId, outcome } = await play(typed("hola ", { every: 50, hold: 30 }));
    const again = await service.finish({ owner, gameId, lastSeq: 1, ipHash: null });
    expect(again).toEqual(outcome);
  });

  it("rejects events generated by code (isTrusted = false)", async () => {
    const events = typed("hola ", { every: 50, hold: 30 }).map((event) => ({ ...event, trusted: false }));
    const { gameId, outcome } = await play(events);
    // The player only gets the category; the exact rule stays in the database (spec §4.9).
    expect(outcome).toMatchObject({ kind: "ok", response: { verdict: "rejected", reason: "unrecognized" } });
    expect(await storedReason(gameId)).toBe("untrusted");
  });

  it("rejects a log with times later than its arrival", async () => {
    const { gameId, outcome } = await play(typed("hola ", { start: 1_000, every: 50, hold: 30 }), { waitBeforeSend: 50 });
    expect(outcome).toMatchObject({ kind: "ok", response: { verdict: "rejected", reason: "unrecognized" } });
    expect(await storedReason(gameId)).toBe("fabricated_timing");
  });

  it("rejects a finish that arrives after the deadline", async () => {
    const { gameId, outcome } = await play(typed("hola ", { every: 50, hold: 30 }), { waitBeforeFinish: 2_000 });
    expect(outcome).toMatchObject({ kind: "ok", response: { verdict: "rejected", reason: "connection" } });
    expect(await storedReason(gameId)).toBe("late");
  });

  it("the finish of someone else's or a missing game is not found", async () => {
    expect(await service.finish({ owner: randomUUID(), gameId: randomUUID(), lastSeq: 0, ipHash: null })).toEqual({ kind: "not_found" });
  });

  it("starting another game closes the previous one", async () => {
    const owner = randomUUID();
    const first = await service.start({ owner, userId: null, language: "en", env: ENV });
    await service.start({ owner, userId: null, language: "en", env: ENV });
    expect(await service.finish({ owner, gameId: first.gameId, lastSeq: 0, ipHash: null })).toEqual({ kind: "closed" });
  });

  it("a game with a session is saved under the user (and with the browser's anonymous cookie)", async () => {
    const [user] = await db
      .insert(users)
      .values({ name: "", email: `${randomUUID()}@example.com`, nick: `t_${randomUUID().slice(0, 8)}` })
      .returning({ id: users.id });
    await verifyEverywhere(db, user.id);
    const { owner, gameId, outcome } = await play(typed("hola ", { every: 50, hold: 30 }), { userId: user.id });
    expect(outcome).toMatchObject({ kind: "ok", response: { verdict: "valid" } });
    expect(outcome).toMatchObject({ kind: "ok", response: { ranking: { kind: "ranked", rank: 1, improved: true } } });
    const [row] = await db.select({ userId: games.userId, anonId: games.anonId }).from(games).where(eq(games.id, gameId));
    expect(row).toEqual({ userId: user.id, anonId: owner });
  });

  it("with an account, no verified level and in a top 10: stays in review, with its PostgreSQL position and no Redis", async () => {
    await emptyBoards(db);
    const [user] = await db
      .insert(users)
      .values({ name: "", email: `${randomUUID()}@example.com`, nick: `t_${randomUUID().slice(0, 8)}` })
      .returning({ id: users.id });
    // 7 words in 1.5 s = 280 WPM in Portuguese on a physical keyboard; with empty rankings, it is first.
    const events = typed("hola ".repeat(7), { every: 40, hold: 30 });
    const { gameId, outcome } = await play(events, { userId: user.id, language: "pt", waitBeforeSend: 1_200 });
    if (outcome.kind !== "ok") throw new Error(outcome.kind);
    expect(outcome.response).toMatchObject({
      wpm: 280,
      verdict: "review",
      ranking: {
        kind: "review",
        verification: { language: "pt", inputType: "physical", targetWpm: 280, requiredWpm: 238, attemptsLeft: 3 },
      },
    });
    const { ranking } = outcome.response as FinishResponse;
    if (ranking.kind !== "review") throw new Error(ranking.kind);
    expect(ranking.rank).toBe(1);
    expect(await db.select().from(bests).where(eq(bests.gameId, gameId))).toEqual([]);
    expect(await leaderboard.position({ language: "pt", inputType: "physical" }, user.id)).toBeNull();
  });
});
