import { describe, expect, it } from "vitest";
import type { TypingEvent } from "@/lib/scoring/types";
import { DEV_ANTICHEAT_CONFIG as C } from "./config";
import { checkEvents, checkSpeed, checkTiming, type ReceivedBatch } from "./rules";
import { inputOnly, typed } from "@/test/typing-events";

const STARTS_AT = 1_000_000;
const DEADLINE = STARTS_AT + 30_000 + 3_000;

function batch(seq: number, arrivedAt: number, events: TypingEvent[]): ReceivedBatch {
  return { seq, arrivedAt, events };
}

describe("checkTiming", () => {
  const honest = [batch(1, STARTS_AT + 3_100, typed("hola ", { start: 100 }))];

  it("accepts an honest game", () => {
    expect(checkTiming(honest, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: STARTS_AT + 31_000, lastSeq: 1 }, C)).toBeNull();
  });

  it("rejects a finish after the deadline", () => {
    expect(checkTiming(honest, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: DEADLINE + 1, lastSeq: 1 }, C)).toBe("late");
  });

  it("rejects a batch that arrives after the deadline", () => {
    const late = [batch(1, DEADLINE + 5, typed("a"))];
    expect(checkTiming(late, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: DEADLINE, lastSeq: 1 }, C)).toBe("late");
  });

  it("rejects if batches are missing relative to lastSeq", () => {
    expect(checkTiming(honest, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: STARTS_AT + 31_000, lastSeq: 2 }, C)).toBe("incomplete");
  });

  it("rejects keystrokes before 0 (during the countdown)", () => {
    const early = [batch(1, STARTS_AT + 3_000, typed("a", { start: -10 }))];
    expect(checkTiming(early, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: STARTS_AT + 31_000, lastSeq: 1 }, C)).toBe("early_input");
  });

  it("rejects events timed after the arrival of their batch (fabricated log)", () => {
    const fabricated = [batch(1, STARTS_AT + 1_000, typed("a", { start: 2_000 }))];
    expect(checkTiming(fabricated, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: STARTS_AT + 31_000, lastSeq: 1 }, C)).toBe("fabricated_timing");
  });

  it("tolerates 250 ms of clock skew", () => {
    const skewed = [batch(1, STARTS_AT + 1_000, typed("a", { start: 1_100, hold: 50 }))];
    expect(checkTiming(skewed, { startsAt: STARTS_AT, deadline: DEADLINE, finishedAt: STARTS_AT + 31_000, lastSeq: 1 }, C)).toBeNull();
  });
});

describe("checkEvents", () => {
  it("accepts human typing on a physical keyboard", () => {
    expect(checkEvents(typed("hola mundo azul casa "), "physical", C)).toBeNull();
  });

  it("rejects events not generated by the user (isTrusted = false)", () => {
    const events = typed("hola ");
    events[1] = { ...events[1], trusted: false };
    expect(checkEvents(events, "physical", C)).toBe("untrusted");
  });

  it("on a physical keyboard rejects text without a keystroke (injected)", () => {
    expect(checkEvents(inputOnly("hola "), "physical", C)).toBe("injected_input");
  });

  it("on touch does not require keystrokes", () => {
    expect(checkEvents(inputOnly("hola mundo "), "touch", C)).toBeNull();
  });

  it("on a physical keyboard rejects any insertion of several letters at once", () => {
    const events: TypingEvent[] = [
      ...typed("ho"),
      { t: 400, type: "down", key: "Unidentified", code: "", trusted: true },
      { t: 401, type: "input", deleted: 0, inserted: "la ", trusted: true },
    ];
    expect(checkEvents(events, "physical", C)).toBe("multi_insert");
  });

  it(`on touch tolerates up to ${C.touchMultiInsertLimit} multi-insertions (autocorrect) and rejects more`, () => {
    const multi = (t: number): TypingEvent => ({ t, type: "input", deleted: 2, inserted: "ola", trusted: true });
    const tolerated = [...inputOnly("ab"), ...Array.from({ length: C.touchMultiInsertLimit }, (_, i) => multi(1_000 + i * 500))];
    expect(checkEvents(tolerated, "touch", C)).toBeNull();
    expect(checkEvents([...tolerated, multi(9_000)], "touch", C)).toBe("multi_insert");
  });

  it("a composed accented letter counts as a single insertion", () => {
    const events: TypingEvent[] = [
      { t: 0, type: "down", key: "Dead", code: "Quote", trusted: true },
      { t: 100, type: "down", key: "a", code: "KeyA", trusted: true },
      { t: 101, type: "input", deleted: 0, inserted: "á", trusted: true },
    ];
    expect(checkEvents(events, "physical", C)).toBeNull();
  });

  it("holding a non-writing key (Shift) does not hide injected text", () => {
    const events: TypingEvent[] = [];
    for (let t = 0; t < 3_000; t += 33) events.push({ t, type: "down", key: "Shift", code: "ShiftLeft", trusted: true });
    events.push(...inputOnly("hola mundo", { start: 10, every: 45 }));
    expect(checkEvents(events.toSorted((a, b) => a.t - b.t), "physical", C)).toBe("injected_input");
  });

  it("each letter needs its own keystroke: holding a key does not hide other injected letters", () => {
    const events: TypingEvent[] = [];
    for (let t = 0; t < 3_000; t += 33) events.push({ t, type: "down", key: "a", code: "KeyA", trusted: true });
    events.push(...inputOnly("hola mundo", { start: 10, every: 45 }));
    expect(checkEvents(events.toSorted((a, b) => a.t - b.t), "physical", C)).toBe("injected_input");
  });

  it("accepts overlapping keystrokes: two keydowns in a row and then their letters", () => {
    const events: TypingEvent[] = [
      { t: 0, type: "down", key: "h", code: "KeyH", trusted: true },
      { t: 5, type: "down", key: "o", code: "KeyO", trusted: true },
      { t: 6, type: "input", deleted: 0, inserted: "h", trusted: true },
      { t: 7, type: "input", deleted: 0, inserted: "o", trusted: true },
    ];
    expect(checkEvents(events, "physical", C)).toBeNull();
  });

  it("a standalone accent (dead key + space) counts as pressed", () => {
    const events: TypingEvent[] = [
      { t: 0, type: "down", key: "Dead", code: "Quote", trusted: true },
      { t: 100, type: "down", key: " ", code: "Space", trusted: true },
      { t: 101, type: "input", deleted: 0, inserted: "´", trusted: true },
    ];
    expect(checkEvents(events, "physical", C)).toBeNull();
  });

  it("is linear: checks 100,000 keystrokes in under a second", () => {
    const events: TypingEvent[] = [];
    for (let i = 0; i < 100_000; i++) {
      const t = (i * 29_000) / 100_000;
      events.push({ t, type: "down", key: "a", code: "KeyA", trusted: true });
      events.push({ t: t + 0.1, type: "input", deleted: 0, inserted: "a", trusted: true });
    }
    const started = performance.now();
    checkEvents(events, "physical", C);
    expect(performance.now() - started).toBeLessThan(1_000);
  });

  it(`rejects inhuman bursts (median < ${C.burstMedianMs} ms over 20 keystrokes)`, () => {
    expect(checkEvents(typed("abcdefghijklmnopqrstuvwxyz", { every: 10, hold: 5 }), "physical", C)).toBe("inhuman_burst");
  });

  it("accepts fast but human bursts", () => {
    expect(checkEvents(typed("abcdefghijklmnopqrstuvwxyz", { every: 40, hold: 30 }), "physical", C)).toBeNull();
  });
});

describe("checkSpeed", () => {
  it("rejects WPM above the ceiling of each category", () => {
    expect(checkSpeed(321, "physical", C)).toBe("inhuman_speed");
    expect(checkSpeed(320, "physical", C)).toBeNull();
    expect(checkSpeed(221, "touch", C)).toBe("inhuman_speed");
    expect(checkSpeed(200, "touch", C)).toBeNull();
  });
});

describe("configuration", () => {
  it("the thresholds come from the configuration it receives, not from code constants", () => {
    const strict = { ...C, burstMedianMs: 50, wpmCeiling: { physical: 200, touch: 150 } };
    const fast = typed("abcdefghijklmnopqrstuvwxyz", { every: 40, hold: 30 });
    expect(checkEvents(fast, "physical", C)).toBeNull();
    expect(checkEvents(fast, "physical", strict)).toBe("inhuman_burst");
    expect(checkSpeed(250, "physical", C)).toBeNull();
    expect(checkSpeed(250, "physical", strict)).toBe("inhuman_speed");
  });
});
